project:
  type: book
  output-dir: docs

book:
  title: "Statistics for the Experimental Bench Biologist"
  subtitle: "Best practice workflows using R"
  date: last-modified
  author:
    - name: "Jeffrey A. Walker"
      email: walker@maine.edu
      affiliation: 
        - name: University of Southern Maine
          city: Portland
          state: ME
          url: https://usm.maine.edu/directories/people/jeffrey-walker/
  license: "CC BY"
  chapters:
    - index.qmd
    - chapters/preface.qmd
    - chapters/intro.qmd
    - chapters/setup.qmd
    - chapters/reading-writing-wrangling.qmd
    - chapters/plotting-models.qmd
    - chapters/uncertainty-sd-and-se.qmd
    - chapters/p-values.qmd
    - chapters/inference-errors.qmd
    - chapters/intro-stat-modeling.qmd
    - chapters/continuous_x.qmd
    - chapters/one-factor.qmd
    - chapters/model-checking.qmd
    - chapters/multiple-testing.qmd
    - chapters/two-factors.qmd
    - chapters/ancova.qmd
    - chapters/lmm.qmd
    - chapters/glm.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 4
editor: source

